---
title: "Mini Essay 5"
author: Yingzhi Zhang
date: today
date-format: long
abstract: "blablablablabla"
format: pdf
header-includes: 
- \usepackage{float}
mainfont: Times New Roman
sansfont: Times New Roman
number-sections: true
bibliography: references.bib
toc: true
---
```{r}
#| include: false
#| warning: false
#| message: false

library(httr)
library(janitor)
library(knitr)
library(tidyverse)
```


```{r}
#| echo: false
#| eval: true
#| warning: false
#| message: false

###Read clean data and make a table
cleaned_data <- read_csv("../mini_essay_5/cleaned_data.csv")

cleaned_data %>% 
  kable(
    col.names = c("Prime Minister", "Birth year", "Death year", "Age at death")
    )

```

```{r}
#| echo: false
#| eval: true
#| warning: false
#| message: false

cleaned_data %>% 
  mutate(
    still_alive = if_else(is.na(died), "Yes", "No"),
    died = if_else(is.na(died), as.integer(2023), died)
  ) %>% 
  mutate(name = as_factor(name)) %>% 
  ggplot(
    aes(x = born, xend = died, y = name, yend = name, color = still_alive)
    ) +
  geom_segment() +
  labs(
    x = "Year of birth", y = "Prime minister", color = "PM is currently alive"
    ) +
  theme_minimal() +
  scale_color_brewer(palette = "Set1") +
  theme(legend.position = "bottom")
```

